# Generated by Django 3.2.4 on 2023-07-01 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpmSpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dID', models.CharField(max_length=10)),
                ('ticket_k', models.CharField(max_length=15, verbose_name='Заявка К')),
                ('client', models.CharField(max_length=200, verbose_name='Клиент')),
                ('type_ticket', models.CharField(max_length=20, verbose_name='Тип заявки')),
                ('manager', models.CharField(max_length=100, verbose_name='Менеджер')),
                ('technolog', models.CharField(max_length=100, verbose_name='Технолог')),
                ('task_otpm', models.TextField(verbose_name='Задача в ОТПМ')),
                ('services', models.JSONField(verbose_name='Перечень требуемых услуг')),
                ('des_tr', models.JSONField(verbose_name='Состав Заявки ТР')),
                ('comment', models.TextField(verbose_name='Примечание')),
                ('created', models.DateTimeField()),
                ('waited', models.DateTimeField()),
                ('duration_process', models.DurationField()),
                ('duration_wait', models.DurationField()),
                ('process', models.BooleanField(default=False, verbose_name='В работе')),
                ('wait', models.BooleanField(default=False, verbose_name='В ожидании')),
                ('projected', models.BooleanField(default=False, verbose_name='Спроектирована')),
                ('evaluative_tr', models.BooleanField(default=False, verbose_name='Оценочное ТР')),
                ('uID', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID куратора')),
                ('trdifperiod', models.CharField(blank=True, max_length=10, null=True, verbose_name='Сложность в часах')),
                ('trcuratorphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон куратора')),
                ('stage', models.CharField(max_length=100, verbose_name='Cтатус заявки СПП')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
