# Generated by Django 3.2.4 on 2023-08-25 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название должности')),
            ],
        ),
        migrations.CreateModel(
            name='OtpmSpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dID', models.CharField(max_length=10)),
                ('ticket_k', models.CharField(max_length=15, verbose_name='Заявка К')),
                ('client', models.CharField(max_length=200, verbose_name='Клиент')),
                ('type_ticket', models.CharField(max_length=20, verbose_name='Тип заявки')),
                ('manager', models.CharField(max_length=100, verbose_name='Менеджер')),
                ('technolog', models.CharField(max_length=100, verbose_name='Технолог')),
                ('task_otpm', models.TextField(verbose_name='Задача в ОТПМ')),
                ('services', models.JSONField(verbose_name='Перечень требуемых услуг')),
                ('des_tr', models.JSONField(verbose_name='Состав Заявки ТР')),
                ('comment', models.TextField(verbose_name='Примечание')),
                ('created', models.DateTimeField()),
                ('waited', models.DateTimeField()),
                ('duration_process', models.DurationField()),
                ('duration_wait', models.DurationField()),
                ('process', models.BooleanField(default=False, verbose_name='В работе')),
                ('wait', models.BooleanField(default=False, verbose_name='В ожидании')),
                ('projected', models.BooleanField(default=False, verbose_name='Спроектирована')),
                ('difficulty', models.CharField(max_length=10, verbose_name='Сложность')),
                ('uID', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID куратора')),
                ('trdifperiod', models.CharField(blank=True, max_length=10, null=True, verbose_name='Сложность в часах')),
                ('trcuratorphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон куратора')),
                ('stage', models.CharField(max_length=100, verbose_name='Cтатус заявки СПП')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHoldPosition',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('hold_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oattr.holdposition', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='OtpmTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_tr', models.CharField(max_length=100, verbose_name='ТР')),
                ('pps', models.CharField(max_length=200, verbose_name='ППС')),
                ('info_tr', models.TextField(blank=True, null=True, verbose_name='Инфо для разработки')),
                ('services', models.JSONField(verbose_name='Перечень требуемых услуг')),
                ('address_cp', models.CharField(max_length=400, verbose_name='Адрес точки подключения')),
                ('place_cp', models.CharField(blank=True, max_length=400, null=True, verbose_name='Место точки подключения')),
                ('vID', models.IntegerField()),
                ('ticket_cp', models.CharField(max_length=10, verbose_name='Точка подключения')),
                ('oattr', models.TextField(verbose_name='Решение ОТПМ')),
                ('titles', models.TextField(blank=True, null=True, verbose_name='Заголовки ТР')),
                ('aid', models.CharField(max_length=10, verbose_name='ID адреса точки подключения')),
                ('tr_without_os', models.BooleanField(default=False, verbose_name='Участие ОС не требуется')),
                ('tr_complex_access', models.BooleanField(default=False, verbose_name='Сложный доступ')),
                ('tr_complex_equip', models.BooleanField(default=False, verbose_name='Нестандартное оборудование')),
                ('tr_turn_off', models.BooleanField(default=False, verbose_name='Отключение')),
                ('tr_complex_access_input', models.TextField(blank=True, null=True, verbose_name='Сложный доступ текст')),
                ('tr_complex_equip_input', models.TextField(blank=True, null=True, verbose_name='Нестандартное оборудование текст')),
                ('tr_turn_off_input', models.TextField(blank=True, null=True, verbose_name='Отключение текст')),
                ('ticket_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='oattr.otpmspp')),
            ],
        ),
    ]
