# Generated by Django 3.2.4 on 2021-06-16 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dID', models.CharField(max_length=10)),
                ('ticket_k', models.CharField(max_length=15, verbose_name='Заявка К')),
                ('client', models.CharField(max_length=50, verbose_name='Клиент')),
                ('type_ticket', models.CharField(max_length=20, verbose_name='Тип заявки')),
                ('manager', models.CharField(max_length=50, verbose_name='Менеджер')),
                ('technolog', models.CharField(max_length=50, verbose_name='Технолог')),
                ('task_otpm', models.TextField(verbose_name='Задача в ОТПМ')),
                ('services', models.JSONField(verbose_name='Перечень требуемых услуг')),
                ('des_tr', models.JSONField(verbose_name='Состав Заявки ТР')),
                ('comment', models.TextField(verbose_name='Примечание')),
                ('version', models.IntegerField(verbose_name='Версия')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('complited', models.DateTimeField(auto_now=True)),
                ('process', models.BooleanField(default=False, verbose_name='В работе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_tr', models.CharField(max_length=100, verbose_name='ТР')),
                ('pps', models.CharField(max_length=100, verbose_name='ППС')),
                ('turnoff', models.BooleanField(default=False, verbose_name='Отключение')),
                ('info_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инфо для разработки')),
                ('oattr', models.TextField(blank=True, null=True, verbose_name='Решение ОТПМ')),
                ('services', models.JSONField(verbose_name='Перечень требуемых услуг')),
                ('kad', models.CharField(max_length=100, verbose_name='КАД')),
                ('vID', models.IntegerField()),
                ('ticket_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tickets.spp')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('ticket_tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tr')),
            ],
        ),
        migrations.CreateModel(
            name='OrtrTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortr', models.TextField(verbose_name='Решение ОРТР')),
                ('ots', models.TextField(blank=True, null=True, verbose_name='Решение ОТС')),
                ('ticket_tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tr')),
            ],
        ),
    ]
