# Generated by Django 3.2.4 on 2021-06-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spp',
            name='client',
            field=models.CharField(max_length=100, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='spp',
            name='manager',
            field=models.CharField(max_length=100, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='spp',
            name='technolog',
            field=models.CharField(max_length=100, verbose_name='Технолог'),
        ),
    ]
