# Generated by Django 3.2.4 on 2021-06-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210617_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tr',
            name='info_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Инфо для разработки'),
        ),
        migrations.AlterField(
            model_name='tr',
            name='kad',
            field=models.CharField(max_length=200, verbose_name='КАД'),
        ),
        migrations.AlterField(
            model_name='tr',
            name='pps',
            field=models.CharField(max_length=200, verbose_name='ППС'),
        ),
    ]
