# Generated by Django 3.2.4 on 2021-08-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210617_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='spp',
            name='wait',
            field=models.BooleanField(default=False, verbose_name='В ожидании'),
        ),
    ]
